import React, { Component, useEffect, useState } from "react";
import Head from "next/head";
import Image from "next/image";

import MainPage from "./../Components/MainPage/MainPage";

export const config = {
  unstable_runtimeJS: false,
};
export default function Home() {
  let [loading, setLoading] = useState(false);
  useEffect(() => {
    setLoading(true);
    setTimeout(() => {
      setLoading(false);
    }, 1000);
  }, []);
  return (
    <div className='MainPage'>
      <Head>
        <title>Funnel Liner</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, user-scalable=no' />
        <link rel='icon' href='images/favicon.png' />
      </Head>

      <>
        {
        loading ? (
          <div className="Preloader">
            <div className="img">
              <img src="../sppiner.gif" />
            </div>
          </div>
        )
        :
        ( <MainPage/>)
      }

      </>
    </div>
  );
}
